### ISSUE TITLE
Configure assets server to read and respond to client hints

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/assets.ubuntu.com#77] opened 2016-02-23 16:54 UTC
It would be great if we could use client hints for responsive images coming from the assets server.

This article explains it much better than I can..

https://www.smashingmagazine.com/2016/01/leaner-responsive-images-client-hints/#the-server-side-of-client-hints

**Comment by nottrobin** [comment] 2017-09-13 20:58
Duplicate of #74

**Closed by nottrobin** 2017-09-13 20:58 UTC
